### ISSUE TITLE
Атака

### ISSUE THREAD

**Issue by Danil228Vasilevich** [Slobodidze/FirstRPG#12]
def fight():
    global myxp
    global animal
    global mydamag
    global xp
    global damag
    playerAtak=0
    print(f"Атаковать? {animal} с ударом {mydamag}")
    print(f"Бежать? от  {animal} то он ударит вас 2 раза с уроном {damag}")
    print("Твой выбор Атака/Бежать")
    playerAtak = input()
    if playerAtak == 'Бежать':
        print(f"Вы решаете спасаться бегством от {animal}")
        myxp == (myxp - damag)*2
        print (f"Вы получаете урон от {animal} у вас осталось здоровья  {myxp} ! ")
    elif playerAtak == "Атака":
         print(f"Вы решаете атаковать {animal}")
         while myxp>=1 or xp>=1:
             xp == mydamag - xp
             myxp == damag - myxp
             print(f"Вы бьете животное с уроном {mydamag}")
             print(f"Вас бьют с уроном {damag}")
             print(f"Увас здоровья {myxp} Здоровье животного {xp}")
             if myxp>=1:
                 print("Вы умерли")
             elif myxp>=1:
                 print("Вы выйграли")
             else:
                 print("Бьемся дальше ")

**Comment by Slobodidze** [comment]
`myxp == (myxp - damag)*2`  - Должно быть   myxp **=** (myxp - damag)*2
xp == mydamag - xp
myxp == damag - myxp
Опять == вместо =. Сравнение, вместо Присваивания Нового значения.
Ко всему мы из Урона вычитаем Жизни, а не наоборот
