### ISSUE TITLE
НАЧАЛО

### ISSUE THREAD

**Issue by Scorpitr0n** [Slobodidze/FirstRPG#4]
*** Вы проснулись от громкого крика. Убрав с лица пальмовый лист, вы осмотрелись вокруг. Вы увидели лишь тропические заросли, где-то в далеке слышался шум волн.
 Вы были одеты в *случайное:
			1. черные порванные шорты, рядом с вами лежала сумка.
			2. длинные штаны с кожаным поясом, порванную, пропахшую рыбой, футболку, а рядом с вами лежала сумка.
			3. странную рубажку с коротким рукавом, на ваших шортах красовались кровавые пятна, а на запястьях были надеты браслеты из ракушек. А рядом с вами лежала сумка*
ДОБАВИТЬ ПРОВЕРИТЬ СУМКУ

ПРОШУ ОТРЕДАКТИРОВАТЬ

**Comment by Danil228Vasilevich** [comment]
дэб

**Comment by Slobodidze** [comment]
Добавлено, смотри функцию start()
