### ISSUE TITLE
Оружейная (work in progress)

### ISSUE THREAD

**Issue by Scorpitr0n** [Slobodidze/FirstRPG#6]
10% с _Берег разбитых кораблей_
Вы нашли корабль с уцелевшей оружейной комнатой
Большой шанс встретить - обезьяну и змею
Средней шанс встретить - никого
Маленький шанс - бронежук
**Оружие и броня **
Роба туземца +4хп
Арбалет 5 по 3,5 урона
Какое-то кол-во воды, еды

if aloc == 3: #Оружейная
print(f'Вы нашли корабль с уцелевшей оружейной комнатой')
                          #Змея(3),Обезъяна(3),БронеЖук(1),КиренРысь(0),Пальмоголовый(0),Пантера(0) = 4
a = random.randint(1, 4) # Генерируем существо
if a <= 3:
print('Здесь Змея')
choice = 6
if 3 < a <= 6:
print('Здесь Обезьяна')
choice = 7
if 6 < a <= 7:
print('Здесь Бронежук ')
choice = 1

**Comment by Danil228Vasilevich** [comment]
повезло повезло

**Comment by Danil228Vasilevich** [comment]
if aloc == 1:
            # Кирена(3),Чихающий еж(3),Пантера(2),Пальмоголовы(1),мартышка(1),бронежук(1) = 11
            a = random.randint(1, 11)  # Генерируем существо
            if a <= 3:
                print('Здесь Змея')
                choice = 6
            if 3 < a <= 6:
                print('Здесь Обезъяна')
                choice = 7
            if 6 < a <= 8:
                print('Здесь БронеЖук')
                choice = 1
            if 8 < a <= 9:
                print('Здесь КиренРысь')
                choice = 3
            if 9 < a <= 10:
                print('Здесь Пальмоголовый')
                choice = 4
            if 10 < a <= 11:
                print('Здесь Пантера')
                choice = 5
11
1
1
1

11111111111111
111
1

11
1
1
1
1
1
1
1
1
1

1
1
1
1
11
1


1
1
1
1
1
1
2


12
12
12
1
21
2121
2
12
12
1
21
2
12
1
21
2
1
21
2
12
12
1
21
21
212121

**Comment by Danil228Vasilevich** [comment]
не то

**Comment by Danil228Vasilevich** [comment]
_как так то **? _**

**Comment by Slobodidze** [comment]
Добавлено. 10% шанс попасть Осмотревшись на локации **Берег разбитых кораблей**
В генератор существ код вставлен
по генерации брони, еды и оружия - пока в "планах"
