### ISSUE TITLE
Сундуки - местоположение и их лут(ВРОДЕ ДОДЕЛАНО)

### ISSUE THREAD

**Issue by Scorpitr0n** [Slobodidze/FirstRPG#8]
Все "Сундуки" будут делится на 4 вида:
1)Мешки - малое кол-во воды - от 2 до 5 дополнительных перемещений(100%)
_Вы нашли мешок с припасами. Теперь вам хватает воды еще на (от 2 до 5 перемещений)._
2)Бочки - среднее кол-во воды - от 4 до 6 дополнительных перемещений(100%)
_Вы нашли уцелевшую бочку. В ней хватает припасов еще на (от 4 до 6 перемещений)._
3)Сундуки - среднее кол-во воды и какое-то оружие* или доспехи* (50%) или большое кол-во воды - от 6 до 8 перемещений(50%)
Оружие на каждой локации будет отличаться(позже пропишу). Каждое оружие на каждой локации будет иметь особый шанс на выпадение из сундука.
_Вы нашли сундук. Открыв его, вы обнаружили, что в нем содержится припасов еще на (от 4 до 6) перемещений и (оружие).**{50%}** _**или**_ Открыв его, вы обнаружили, что в нем содержится припасов еще на (от 6 до 8) перемещений._
4) Особые сундуки  - в них входит ТОЛЬКО какое-либо оружие(45%) или броню(45%)
Такими являются:
-**Сундук капитана**. Он содержит **Испанская сабля** или **Комплект пирата**
-**Сундук Джунглей**. Он содержит **Копьё джунглей** или **Доспехи джунглей**
-**Сундук Туземцев**. Он содержит **Лук туземцев** или **Роба туземца**
_Поздравляем! Вы нашли уникальный сундук (что за сундук). В нем хранится (оружие) _**или**_ (броня)
**Расположение**
ЧАЩА:
-3 мешка(шанс найти каждый - 60%). После нахождения первого вы также находите **Палку-копалку**.
-1 бочка(шанс найти - 30%)
-1 сундук (УНИКАЛЬНЫЙ ШАНС НАЙТИ - ***Каменный молот**- 90%)(шанс найти сундук - 70%):
**Змеиный пояс** - 70%
**Охотничий нож** - 0%
**Копьё джунглей**- 5%
**Доспехи джунглей** - 3%
-Сундук Джунглей(шанс найти - 10%)
Рысья пещера:
-5 мешков(шанс найти каждый - 80%). "Ищем?"
-Нет бочек
-1 сундук (шанс найти - 90%):
**Охотничий нож** - 30%
**Каменный молот** - 40% 
**Змеиный пояс** - 50%
**Роба туземца** - 1%
**Лук туземцев** - 2%
-Нет особого сундука
Берег разбитых кораблей:
-8 мешков(шанс найти каждый - 70%)
-8 бочек(шанс найти - 60%)
-3 сундука(шанс найти - 50%):
**Испанская сабля** - 10%
**Комплект пирата** - 20%
**Охотничий нож** - 30%
**Роба туземца** - 5%
-**Сундук капитана**(шанс найти - 15%)
Оружейная:
-1 мешок(шанс - 90%)
-3 бочки(шанс найти - 100%)
-Сундук с оружием:
**Испанская сабля** - 30%
**Охотничий нож**  - 50%
**Лук туземцев** - 20%
Лагерь туземцев:
-10 мешков(шанс найти - 40%)
-5 бочек(шанс найти - 50%)
-5 сундуков(шанс найти - 50%):
Шанс на все оружия и броню кроме **Лук туземцев** и **Роба туземца** одинаковый - 45%
-Сундук Туземцев(шанс найти - 70%)
**Лук туземцев** - 50%
**Роба туземца** - 50%
**_ИЩЕМ?_**

**Comment by Danil228Vasilevich** [comment]
пойдет
