### ISSUE TITLE
Оно? Тестовый иссуе

### ISSUE THREAD

**Issue by Scorpitr0n** [Slobodidze/FirstRPG#9]
if loc == 2:
        o = random.randint(1, 10)
        if o == 1:
            aloc = 3
            print(f'Вы нашли корабль с уцелевшей оружейной комнатой')
            gen_animal(loc)

if aloc == 3: #Оружейная
print(f'Вы нашли корабль с уцелевшей оружейной комнатой')
#Змея(3),Обезъяна(3),БронеЖук(1),КиренРысь(0),Пальмоголовый(0),Пантера(0) = 7
a = random.randint(1, 7) # Генерируем существо
if a <= 3:
print('Здесь Змея')
choice = 6
if 3 < a <= 6:
print('Здесь Обезьяна')
choice = 7
if 6 < a <= 7:
print('Здесь Бронежук ')
choice = 1

**Comment by Danil228Vasilevich** [comment]
пайдет

**Comment by Slobodidze** [comment]
Добавлено в функцию gen_loc()
